// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testAppVersions(t *testing.T) {
	t.Parallel()

	query := AppVersions()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testAppVersionsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppVersion{}
	if err = randomize.Struct(seed, o, appVersionDBTypes, true, appVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AppVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAppVersionsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppVersion{}
	if err = randomize.Struct(seed, o, appVersionDBTypes, true, appVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := AppVersions().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AppVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAppVersionsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppVersion{}
	if err = randomize.Struct(seed, o, appVersionDBTypes, true, appVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AppVersionSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AppVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAppVersionsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppVersion{}
	if err = randomize.Struct(seed, o, appVersionDBTypes, true, appVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := AppVersionExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if AppVersion exists: %s", err)
	}
	if !e {
		t.Errorf("Expected AppVersionExists to return true, but got false.")
	}
}

func testAppVersionsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppVersion{}
	if err = randomize.Struct(seed, o, appVersionDBTypes, true, appVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	appVersionFound, err := FindAppVersion(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if appVersionFound == nil {
		t.Error("want a record, got nil")
	}
}

func testAppVersionsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppVersion{}
	if err = randomize.Struct(seed, o, appVersionDBTypes, true, appVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = AppVersions().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testAppVersionsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppVersion{}
	if err = randomize.Struct(seed, o, appVersionDBTypes, true, appVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := AppVersions().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testAppVersionsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	appVersionOne := &AppVersion{}
	appVersionTwo := &AppVersion{}
	if err = randomize.Struct(seed, appVersionOne, appVersionDBTypes, false, appVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}
	if err = randomize.Struct(seed, appVersionTwo, appVersionDBTypes, false, appVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = appVersionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = appVersionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AppVersions().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testAppVersionsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	appVersionOne := &AppVersion{}
	appVersionTwo := &AppVersion{}
	if err = randomize.Struct(seed, appVersionOne, appVersionDBTypes, false, appVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}
	if err = randomize.Struct(seed, appVersionTwo, appVersionDBTypes, false, appVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = appVersionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = appVersionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AppVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func appVersionBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *AppVersion) error {
	*o = AppVersion{}
	return nil
}

func appVersionAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *AppVersion) error {
	*o = AppVersion{}
	return nil
}

func appVersionAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *AppVersion) error {
	*o = AppVersion{}
	return nil
}

func appVersionBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *AppVersion) error {
	*o = AppVersion{}
	return nil
}

func appVersionAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *AppVersion) error {
	*o = AppVersion{}
	return nil
}

func appVersionBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *AppVersion) error {
	*o = AppVersion{}
	return nil
}

func appVersionAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *AppVersion) error {
	*o = AppVersion{}
	return nil
}

func appVersionBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *AppVersion) error {
	*o = AppVersion{}
	return nil
}

func appVersionAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *AppVersion) error {
	*o = AppVersion{}
	return nil
}

func testAppVersionsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &AppVersion{}
	o := &AppVersion{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, appVersionDBTypes, false); err != nil {
		t.Errorf("Unable to randomize AppVersion object: %s", err)
	}

	AddAppVersionHook(boil.BeforeInsertHook, appVersionBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	appVersionBeforeInsertHooks = []AppVersionHook{}

	AddAppVersionHook(boil.AfterInsertHook, appVersionAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	appVersionAfterInsertHooks = []AppVersionHook{}

	AddAppVersionHook(boil.AfterSelectHook, appVersionAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	appVersionAfterSelectHooks = []AppVersionHook{}

	AddAppVersionHook(boil.BeforeUpdateHook, appVersionBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	appVersionBeforeUpdateHooks = []AppVersionHook{}

	AddAppVersionHook(boil.AfterUpdateHook, appVersionAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	appVersionAfterUpdateHooks = []AppVersionHook{}

	AddAppVersionHook(boil.BeforeDeleteHook, appVersionBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	appVersionBeforeDeleteHooks = []AppVersionHook{}

	AddAppVersionHook(boil.AfterDeleteHook, appVersionAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	appVersionAfterDeleteHooks = []AppVersionHook{}

	AddAppVersionHook(boil.BeforeUpsertHook, appVersionBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	appVersionBeforeUpsertHooks = []AppVersionHook{}

	AddAppVersionHook(boil.AfterUpsertHook, appVersionAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	appVersionAfterUpsertHooks = []AppVersionHook{}
}

func testAppVersionsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppVersion{}
	if err = randomize.Struct(seed, o, appVersionDBTypes, true, appVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AppVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAppVersionsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppVersion{}
	if err = randomize.Struct(seed, o, appVersionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(appVersionColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := AppVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAppVersionsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppVersion{}
	if err = randomize.Struct(seed, o, appVersionDBTypes, true, appVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAppVersionsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppVersion{}
	if err = randomize.Struct(seed, o, appVersionDBTypes, true, appVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AppVersionSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAppVersionsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppVersion{}
	if err = randomize.Struct(seed, o, appVersionDBTypes, true, appVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AppVersions().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	appVersionDBTypes = map[string]string{`ID`: `integer`, `Name`: `text`}
	_                 = bytes.MinRead
)

func testAppVersionsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(appVersionPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(appVersionAllColumns) == len(appVersionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AppVersion{}
	if err = randomize.Struct(seed, o, appVersionDBTypes, true, appVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AppVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, appVersionDBTypes, true, appVersionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testAppVersionsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(appVersionAllColumns) == len(appVersionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AppVersion{}
	if err = randomize.Struct(seed, o, appVersionDBTypes, true, appVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AppVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, appVersionDBTypes, true, appVersionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(appVersionAllColumns, appVersionPrimaryKeyColumns) {
		fields = appVersionAllColumns
	} else {
		fields = strmangle.SetComplement(
			appVersionAllColumns,
			appVersionPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := AppVersionSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testAppVersionsUpsert(t *testing.T) {
	t.Parallel()

	if len(appVersionAllColumns) == len(appVersionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := AppVersion{}
	if err = randomize.Struct(seed, &o, appVersionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AppVersion: %s", err)
	}

	count, err := AppVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, appVersionDBTypes, false, appVersionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AppVersion struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AppVersion: %s", err)
	}

	count, err = AppVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
